//
//  TuyaSmartSceneLogModel.h
//  TuyaSmartSceneKit
//
//  Copyright (c) 2014-2021 Tuya Inc. (https://developer.tuya.com)

#import <Foundation/Foundation.h>

NS_ASSUME_NONNULL_BEGIN

@class TuyaSmartSceneLogData;

/// @brief TuyaSmartSceneLogModel provides extra attributes to create a log list model for a scene.
@interface TuyaSmartSceneLogModel : NSObject

/// A list of log data for a scene.
@property (nonatomic, strong) NSArray<TuyaSmartSceneLogData *> * datas;

/// The number of scene log entries.
@property (nonatomic, assign) NSInteger totalCount;

@end

/// @brief TuyaSmartSceneLogData provides extra attributes to create log data.
@interface TuyaSmartSceneLogData : NSObject

/// The ID of a log event.
@property (nonatomic, strong) NSString *eventId;

/// The result of running a scene.
@property (nonatomic, assign) NSInteger execResult;

/// The result message that is returned after a scene is run.
@property (nonatomic, strong) NSString *execResultMsg;

/// The time when a scene is run.
@property (nonatomic, strong) NSString *execTime;

/// The error message that is returned after a scene is run.
@property (nonatomic, strong) NSString *failureCause;

/// The error code.
@property (nonatomic, assign) NSInteger failureCode;

/// The owner ID of a scene log entry.
@property (nonatomic, strong) NSString *ownerId;

/// The rule ID of the scene.
@property (nonatomic, strong) NSString *ruleId;

/// The rule name.
@property (nonatomic, strong) NSString *ruleName;

/// The type of scene. Valid values: `1` means a tap-to-run scene and `2` means an automation scene.
@property (nonatomic, assign) NSInteger sceneType;

/// The user ID.
@property (nonatomic, strong) NSString *uid;

/// This data is not generated by the service. This property can be set to customize the display style.
@property (nonatomic, strong) NSString *detailTime;

/// This data is not generated by the service. This property can be set to sort the list by category and customize the display style. Valid values: `0` means to sort the list by the first index. `1` means to sort the list by the middle index. `2` means to sort the list by the last index. `-1` means no index is used when only one item is managed.
@property (nonatomic, assign) NSInteger indexType;

@end

NS_ASSUME_NONNULL_END
